# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0004_update_to_0003_upstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='apnsdevice',
            name='fcm_token',
            field=models.TextField(null=True),
        ),
    ]
